name: Auto Cancel
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: Hello
                required: true
                description: A cheerful word
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 120
